In [27]:
import pandas as pd
import numpy as np

df_gerentes= pd.read_excel("gerentes_lojas.xlsx")
df_vendas= pd.read_csv("vendas_tech.csv", low_memory=False)

display(df_gerentes)
display(df_vendas)

             Loja   Gerente  Meta_Mensal
0       São Paulo    Carlos        50000
1  Rio de Janeiro  Fernanda        60000
2        Curitiba   Roberto        45000
3  Belo Horizonte   Juliana        55000
4          Recife    Marcos        48000
5    Porto Alegre     Pedro        42000
6        Salvador       Ana        52000

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,Data_Base
0,1,2023-06-08,São Paulo,Mouse Gamer,120.0,1,Cliente_4095,2025-01-01
1,2,2023-03-01,Belo Horizonte,iPhone 14,5500.0,1,Cliente_8750,NaN
2,3,2023-02-25,NaN,"Monitor 27""",1200.0,1,Cliente_14859,NaN
3,4,2024-11-19,RIO DE JANEIRO,Mouse Gamer,120.0,2,Cliente_17343,NaN
4,5,2024-01-27,Rio de Janeiro,Smartphone Samsung,2200.0,1,Cliente_23377,NaN
...,...,...,...,...,...,...,...,...
100095,94091,2023-10-20,Porto Alegre,iPhone 14,5500.0,1,Cliente_11755,NaN
100096,52883,2024-03-17,Porto Alegre,Notebook Dell,3500.0,2,Cliente_12879,NaN
100097,65070,2023-06-19,Belo Horizonte,Smartphone Samsung,2200.0,2,Cliente_8160,NaN
100098,94031,2024-06-14,Salvador,iPhone 14,5500.0,2,Cliente_28545,NaN
100099,36755,2023-01-03,São Paulo,Notebook HP,3200.0,2,Cliente_3274,NaN

### Inspeção da base de dados 
alguns comandos importantes

In [28]:
#display(df_vendas.head(15))       #.head() serve para ver a quantidade linhas que desejar do começo   ou .tail() a quantidade das ultimas linha da base de dados
#display(df_vendas.tail(5))
#display(df_vendas.sample(5))      # o .sample() pegua a quantidade linhas aleatórias que desejar para amostra ou testes
#display(df_vendas.shape)          # calcula a quantidade linha e colunas e armazena em uma tupla
#display(df_vendas.columns)        # Mostra a quantidade de colunas e seus respectivos nomes
display(df_vendas.info())          # Pegar as informaçoes da base de dados
display(df_vendas.describe())     # .describe() pega os valores e separa a media o max e min valor etc

<class 'pandas.DataFrame'>
RangeIndex: 100100 entries, 0 to 100099
Data columns (total 8 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   ID_Pedido       100100 non-null  int64
 1   Data            100100 non-null  str
 2   Loja            98099 non-null   str
 3   Produto         100100 non-null  str
 4   Preco_Unitario  100100 non-null  float64
 5   Qtd             100100 non-null  int64
 6   Cliente         100100 non-null  str
 7   Data_Base       1 non-null       str
dtypes: float64(1), int64(2), str(5)
memory usage: 6.1 MB

None

           ID_Pedido  Preco_Unitario            Qtd
count  100100.000000   100100.000000  100100.000000
mean    50004.810180     2000.204595       1.499101
std     28866.872543     1841.050733       1.241605
min         1.000000       40.000000       1.000000
25%     25008.750000      120.000000       1.000000
50%     50004.500000     1200.000000       1.000000
75%     75002.250000     3200.000000       1.000000
max    100000.000000     5500.000000      10.000000

### Tratamento dos dados

In [29]:
#display(df_vendas['Loja'])
#display(df_vendas[["Loja","Cliente"]])

#Colunas 
# .drop excluir alguma coluna
df_analise = df_vendas.drop(columns=["Data_Base"])  


#Nulos
#.dropna() Excluie todas a linhas que possuem algum valor vazio
#df_analise= df_analise.dropna()

df_analise["Loja"]= df_analise["Loja"].fillna("Online")

# tipos de dados
#pd.to_datetime serve para formatar as datas do dataframe, checando no info()
df_analise["Data"]= pd.to_datetime(df_analise["Data"], format="%Y-%m-%d") 
df_analise["Loja"] = df_analise["Loja"].str.strip()
df_analise["Loja"] = df_analise["Loja"].str.title()

#Removendo duplicatas
df_analise= df_analise.drop_duplicates(subset=["ID_Pedido"])



display(df_analise)
display(df_analise.info())

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente
0,1,2023-06-08,São Paulo,Mouse Gamer,120.0,1,Cliente_4095
1,2,2023-03-01,Belo Horizonte,iPhone 14,5500.0,1,Cliente_8750
2,3,2023-02-25,Online,"Monitor 27""",1200.0,1,Cliente_14859
3,4,2024-11-19,Rio De Janeiro,Mouse Gamer,120.0,2,Cliente_17343
4,5,2024-01-27,Rio De Janeiro,Smartphone Samsung,2200.0,1,Cliente_23377
...,...,...,...,...,...,...,...
99995,99996,2023-01-24,São Paulo,Mouse Gamer,120.0,2,Cliente_13732
99996,99997,2024-08-28,Rio De Janeiro,Cabo HDMI,40.0,1,Cliente_25058
99997,99998,2024-03-18,Curitiba,Smartphone Samsung,2200.0,2,Cliente_28864
99998,99999,2023-11-04,Porto Alegre,iPhone 14,5500.0,1,Cliente_4205
99999,100000,2024-06-15,Curitiba,Teclado Mecânico,250.0,1,Cliente_12237

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 7 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   ID_Pedido       100000 non-null  int64
 1   Data            100000 non-null  datetime64[us]
 2   Loja            100000 non-null  str
 3   Produto         100000 non-null  str
 4   Preco_Unitario  100000 non-null  float64
 5   Qtd             100000 non-null  int64
 6   Cliente         100000 non-null  str
dtypes: datetime64[us](1), float64(1), int64(2), str(3)
memory usage: 5.3 MB

None

In [30]:
#criar novas colunas

#faturamento
df_analise["Faturamento"] = df_analise["Qtd"] * df_analise["Preco_Unitario"]

#Forma de venda
df_analise["Forma_de_venda"] = np.where(df_analise["Loja"] == "Online","Online", "Presencial")

#Região
display(df_analise["Loja"].unique())

dic_regiao= {'São Paulo': "Sudeste", 'Belo Horizonte' :"Sudeste", 'Online':'Online', 'Rio De Janeiro' :"Sudeste",
'Salvador': "Nordeste", 'Recife': "Nordeste", 'Curitiba': "Sul", 'Porto Alegre': "Sul"}

df_analise["Região"] = df_analise["Loja"].map(dic_regiao)

display(df_analise)
display(df_analise.isna().sum())

<StringArray>
[     'São Paulo', 'Belo Horizonte',         'Online', 'Rio De Janeiro',
       'Salvador',         'Recife',       'Curitiba',   'Porto Alegre']
Length: 8, dtype: str

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,Faturamento,Forma_de_venda,Região
0,1,2023-06-08,São Paulo,Mouse Gamer,120.0,1,Cliente_4095,120.0,Presencial,Sudeste
1,2,2023-03-01,Belo Horizonte,iPhone 14,5500.0,1,Cliente_8750,5500.0,Presencial,Sudeste
2,3,2023-02-25,Online,"Monitor 27""",1200.0,1,Cliente_14859,1200.0,Online,Online
3,4,2024-11-19,Rio De Janeiro,Mouse Gamer,120.0,2,Cliente_17343,240.0,Presencial,Sudeste
4,5,2024-01-27,Rio De Janeiro,Smartphone Samsung,2200.0,1,Cliente_23377,2200.0,Presencial,Sudeste
...,...,...,...,...,...,...,...,...,...,...
99995,99996,2023-01-24,São Paulo,Mouse Gamer,120.0,2,Cliente_13732,240.0,Presencial,Sudeste
99996,99997,2024-08-28,Rio De Janeiro,Cabo HDMI,40.0,1,Cliente_25058,40.0,Presencial,Sudeste
99997,99998,2024-03-18,Curitiba,Smartphone Samsung,2200.0,2,Cliente_28864,4400.0,Presencial,Sul
99998,99999,2023-11-04,Porto Alegre,iPhone 14,5500.0,1,Cliente_4205,5500.0,Presencial,Sul
99999,100000,2024-06-15,Curitiba,Teclado Mecânico,250.0,1,Cliente_12237,250.0,Presencial,Sul

ID_Pedido         0
Data              0
Loja              0
Produto           0
Preco_Unitario    0
Qtd               0
Cliente           0
Faturamento       0
Forma_de_venda    0
Região            0
dtype: int64

In [31]:
#Analisar e Filtrar informações

df_analise = df_analise.sort_values(by="Data")
df_analise = df_analise.reset_index(drop=True)



# Localizar com o .loc, ele procuro por coluna e nome da linha
id_pedido = 4 
loja= df_analise.loc[3,"Loja"] 
produto= df_analise.loc[3,"Produto"]
cliente= df_analise.loc[3,"Cliente"]
print(loja, produto, cliente)

# Localizar pelo Iloc procura por posição
id_pedido= 4
loja= df_analise.iloc[3,2] 
produto= df_analise.iloc[3,3]
cliente= df_analise.iloc[3,6]
print(loja, produto, cliente)



#Condicional
#Trazer o resultado o id_pedido = 4

df_Id_pedido= df_analise[df_analise["ID_Pedido"] == 4]

display(df_analise)
display(df_Id_pedido)


#Exportar pedaços da base

df_vendas_sp= df_analise[df_analise["Loja"] == "São Paulo"]

df_vendas_sp.to_csv("Vendas São Paulo.csv", index=True)

# Exportar as vendas de 2024 colocando condição
df_analise_2024 = df_analise[df_analise["Data"].dt.year == 2024]

#Dupla condição colocar em parenteses por garantida de não dar erro no codigo
df_vendas_HDMI_sul= df_analise[(df_analise["Produto"] == "Cabo HDMI") & (df_analise["Região"] == "Sul")]



display(df_vendas_HDMI_sul)

São Paulo Teclado Mecânico Cliente_22822
São Paulo Teclado Mecânico Cliente_22822

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,Faturamento,Forma_de_venda,Região
0,34750,2023-01-01,Rio De Janeiro,Notebook HP,3200.0,1,Cliente_9014,3200.0,Presencial,Sudeste
1,13699,2023-01-01,Rio De Janeiro,Teclado Mecânico,250.0,1,Cliente_24330,250.0,Presencial,Sudeste
2,81394,2023-01-01,Porto Alegre,Teclado Mecânico,250.0,1,Cliente_9758,250.0,Presencial,Sul
3,251,2023-01-01,São Paulo,Teclado Mecânico,250.0,3,Cliente_22822,750.0,Presencial,Sudeste
4,77068,2023-01-01,Rio De Janeiro,Notebook Dell,3500.0,1,Cliente_554,3500.0,Presencial,Sudeste
...,...,...,...,...,...,...,...,...,...,...
99995,43207,2024-12-30,Belo Horizonte,Notebook Dell,3500.0,2,Cliente_15893,7000.0,Presencial,Sudeste
99996,3183,2024-12-30,Salvador,Mouse Gamer,120.0,1,Cliente_4075,120.0,Presencial,Nordeste
99997,9461,2024-12-30,Porto Alegre,Teclado Mecânico,250.0,1,Cliente_22763,250.0,Presencial,Sul
99998,2793,2024-12-30,Salvador,Notebook Dell,3500.0,1,Cliente_24692,3500.0,Presencial,Nordeste
99999,91693,2024-12-30,São Paulo,iPhone 14,5500.0,1,Cliente_17362,5500.0,Presencial,Sudeste

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,Faturamento,Forma_de_venda,Região
94183,4,2024-11-19,Rio De Janeiro,Mouse Gamer,120.0,2,Cliente_17343,240.0,Presencial,Sudeste

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,Faturamento,Forma_de_venda,Região
15,70138,2023-01-01,Porto Alegre,Cabo HDMI,40.0,1,Cliente_9348,40.0,Presencial,Sul
50,97659,2023-01-01,Curitiba,Cabo HDMI,40.0,1,Cliente_58,40.0,Presencial,Sul
83,42051,2023-01-01,Curitiba,Cabo HDMI,40.0,10,Cliente_16622,400.0,Presencial,Sul
97,37130,2023-01-01,Porto Alegre,Cabo HDMI,40.0,1,Cliente_22886,40.0,Presencial,Sul
98,49140,2023-01-01,Porto Alegre,Cabo HDMI,40.0,1,Cliente_24445,40.0,Presencial,Sul
...,...,...,...,...,...,...,...,...,...,...
99878,35127,2024-12-30,Curitiba,Cabo HDMI,40.0,2,Cliente_20687,80.0,Presencial,Sul
99926,75695,2024-12-30,Porto Alegre,Cabo HDMI,40.0,1,Cliente_29587,40.0,Presencial,Sul
99931,47774,2024-12-30,Porto Alegre,Cabo HDMI,40.0,2,Cliente_14363,80.0,Presencial,Sul
99950,64473,2024-12-30,Porto Alegre,Cabo HDMI,40.0,2,Cliente_11598,80.0,Presencial,Sul
99964,78584,2024-12-30,Curitiba,Cabo HDMI,40.0,1,Cliente_21307,40.0,Presencial,Sul

In [32]:
# Analise por Agrupamento com o grupyby ou seja colocando uma coluna dentro dessa função vai pegar somente uma vez cada dado dessa coluna

analise_lojas = df_analise[["Loja", "Faturamento"]].groupby("Loja").sum()
analise_lojas = analise_lojas.sort_values(by= "Faturamento", ascending= False)
analise_lojas = analise_lojas.reset_index()
analise_lojas["Faturamento"] = analise_lojas["Faturamento"].map("R${:,.2f}".format)  # Ponto de atenção aqui: só inclua formatação de texto caso tenha finalizado toda operação, porque os valores passam as ser texto após a formatação

display(analise_lojas)

# Pegando agora as vendas online e fazendo um ranking de faturamento
df_vendas_online= df_analise[df_analise["Loja"]== "Online"]
df_produtos_online= df_vendas_online[["Produto", "Qtd"]].groupby("Produto").sum()
df_produtos_online = df_produtos_online.sort_values(by="Qtd", ascending=False)

# Mudando o nome da coluna Qtd para total de vendas usando a função rename
df_produtos_online = df_produtos_online.rename(columns={"Qtd": "Total de Vendas"})

display(df_vendas_online)
display(df_produtos_online)

             Loja      Faturamento
0        Salvador  R$42,300,610.00
1  Rio De Janeiro  R$42,294,720.00
2          Recife  R$42,190,390.00
3       São Paulo  R$42,090,690.00
4  Belo Horizonte  R$41,714,890.00
5    Porto Alegre  R$41,678,460.00
6        Curitiba  R$41,121,720.00
7          Online   R$6,080,850.00

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,Faturamento,Forma_de_venda,Região
21,42190,2023-01-01,Online,Notebook Dell,3500.0,1,Cliente_20957,3500.0,Online,Online
84,71409,2023-01-01,Online,Smartphone Samsung,2200.0,1,Cliente_13248,2200.0,Online,Online
150,81764,2023-01-02,Online,Notebook Dell,3500.0,1,Cliente_9372,3500.0,Online,Online
164,84361,2023-01-02,Online,Notebook HP,3200.0,2,Cliente_16773,6400.0,Online,Online
251,37480,2023-01-02,Online,Notebook HP,3200.0,5,Cliente_1678,16000.0,Online,Online
...,...,...,...,...,...,...,...,...,...,...
99843,95096,2024-12-29,Online,iPhone 14,5500.0,1,Cliente_25495,5500.0,Online,Online
99898,8028,2024-12-30,Online,Smartphone Samsung,2200.0,1,Cliente_20679,2200.0,Online,Online
99913,38943,2024-12-30,Online,Notebook HP,3200.0,1,Cliente_18490,3200.0,Online,Online
99963,42794,2024-12-30,Online,Notebook HP,3200.0,1,Cliente_1868,3200.0,Online,Online
99983,55643,2024-12-30,Online,Mouse Gamer,120.0,2,Cliente_20362,240.0,Online,Online

                    Total de Vendas
Produto
Notebook HP                     442
Cabo HDMI                       403
iPhone 14                       390
Mouse Gamer                     379
Notebook Dell                   369
Teclado Mecânico                343
Monitor 27"                     332
Smartphone Samsung              311

In [38]:
# Multiplos agrupamentos, analise de ranking por loja e produto 
# Quais produtos venderam mais por produtos e por lojas 

analise_produtos_em_lojas = df_analise[["Loja","Produto","Qtd"]].groupby(["Loja", "Produto"]).sum()

# Quais lojas mais venderam os produtos
analise_lojas_em_produtos = df_analise[["Loja","Produto","Qtd"]].groupby(["Produto", "Loja"]).sum()


with pd.option_context("display.max_rows", None):
    display(analise_produtos_em_lojas)
    display(analise_lojas_em_produtos)

                                    Qtd
Loja           Produto
Belo Horizonte Cabo HDMI           2636
               Monitor 27"         2625
               Mouse Gamer         2465
               Notebook Dell       2654
               Notebook HP         2775
               Smartphone Samsung  2597
               Teclado Mecânico    2609
               iPhone 14           2478
Curitiba       Cabo HDMI           2698
               Monitor 27"         2626
               Mouse Gamer         2600
               Notebook Dell       2517
               Notebook HP         2529
               Smartphone Samsung  2444
               Teclado Mecânico    2742
               iPhone 14           2652
Online         Cabo HDMI            403
               Monitor 27"          332
               Mouse Gamer          379
               Notebook Dell        369
               Notebook HP          442
               Smartphone Samsung   311
               Teclado Mecânico     343
               iPhone 14            390
Porto Alegre   Cabo HDMI           2571
               Monitor 27"         2655
               Mouse Gamer         2611
               Notebook Dell       2770
               Notebook HP         2511
               Smartphone Samsung  2603
               Teclado Mecânico    2598
               iPhone 14           2540
Recife         Cabo HDMI           2534
               Monitor 27"         2647
               Mouse Gamer         2639
               Notebook Dell       2566
               Notebook HP         2651
               Smartphone Samsung  2660
               Teclado Mecânico    2775
               iPhone 14           2652
Rio De Janeiro Cabo HDMI           2747
               Monitor 27"         2798
               Mouse Gamer         2652
               Notebook Dell       2534
               Notebook HP         2614
               Smartphone Samsung  2626
               Teclado Mecânico    2548
               iPhone 14           2702
Salvador       Cabo HDMI           2566
               Monitor 27"         2545
               Mouse Gamer         2711
               Notebook Dell       2512
               Notebook HP         2785
               Smartphone Samsung  2627
               Teclado Mecânico    2579
               iPhone 14           2671
São Paulo      Cabo HDMI           2649
               Monitor 27"         2796
               Mouse Gamer         2714
               Notebook Dell       2535
               Notebook HP         2592
               Smartphone Samsung  2476
               Teclado Mecânico    2589
               iPhone 14           2735

                                    Qtd
Produto            Loja
Cabo HDMI          Belo Horizonte  2636
                   Curitiba        2698
                   Online           403
                   Porto Alegre    2571
                   Recife          2534
                   Rio De Janeiro  2747
                   Salvador        2566
                   São Paulo       2649
Monitor 27"        Belo Horizonte  2625
                   Curitiba        2626
                   Online           332
                   Porto Alegre    2655
                   Recife          2647
                   Rio De Janeiro  2798
                   Salvador        2545
                   São Paulo       2796
Mouse Gamer        Belo Horizonte  2465
                   Curitiba        2600
                   Online           379
                   Porto Alegre    2611
                   Recife          2639
                   Rio De Janeiro  2652
                   Salvador        2711
                   São Paulo       2714
Notebook Dell      Belo Horizonte  2654
                   Curitiba        2517
                   Online           369
                   Porto Alegre    2770
                   Recife          2566
                   Rio De Janeiro  2534
                   Salvador        2512
                   São Paulo       2535
Notebook HP        Belo Horizonte  2775
                   Curitiba        2529
                   Online           442
                   Porto Alegre    2511
                   Recife          2651
                   Rio De Janeiro  2614
                   Salvador        2785
                   São Paulo       2592
Smartphone Samsung Belo Horizonte  2597
                   Curitiba        2444
                   Online           311
                   Porto Alegre    2603
                   Recife          2660
                   Rio De Janeiro  2626
                   Salvador        2627
                   São Paulo       2476
Teclado Mecânico   Belo Horizonte  2609
                   Curitiba        2742
                   Online           343
                   Porto Alegre    2598
                   Recife          2775
                   Rio De Janeiro  2548
                   Salvador        2579
                   São Paulo       2589
iPhone 14          Belo Horizonte  2478
                   Curitiba        2652
                   Online           390
                   Porto Alegre    2540
                   Recife          2652
                   Rio De Janeiro  2702
                   Salvador        2671
                   São Paulo       2735